### ISSUE TITLE
Did you mean to put "Copyright (c) 2017 gatsbyjs" in the LICENSE file?

### ISSUE THREAD

**Issue by willowell** [arsmth/gatsby-responsive-nav#1]
I found your nav component a few days ago, and I am interested in using it, but I am confused by the copyright you put in the license.

**Comment by arsmth** [comment]
That is just the default gatsby license. You’re free to do whatever you want with this repo, just note that it isn’t maintained and code may be outdated. 😁

**Comment by willowell** [comment]
Oh, okay! That's good to know. Thank you so much for licensing your repo that way, then!

I've been breaking my brain looking around for an experimenting with different navigation bar components.
